import '../scss/style.scss'
import '../blocks/slider/slider.js'
import '../blocks/upper-menu/upper-menu.js'
import '../blocks/menu-header/menu-header.js'
import '../blocks/menu-background/menu-background.js'
//снизу размер текстового описания у картинки компании под высоту этой картинки
//import '../blocks/info/info.js'
import '../blocks/read-more/read-more.js'
import '../blocks/menu/menu.js'
import '../blocks/menu-background-modal/menu-background-modal.js'
import '../blocks/phone-modal/phone-modal.js'
import '../blocks/chat-modal/chat-modal.js'
import '../blocks/menu-phone/menu-phone.js'
